### ISSUE TITLE
jrubyfxml sensitive to spaces in xml

### ISSUE THREAD

**Issue by JC-LL** [byteit101/JRubyFXML#2]
I am trying to use jrubyfx and fxml (generated by Gluon). I modified fxml to add an action :  
<Button  onAction="#start"...>

But, depending on the number of spaces between "Button" and "onAction", my application crashes...The required number is 2 blank spaces ! 

My settings : 
- jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +jit [linux-x86_64]
- jrubyfx (1.2.0 java)
- jrubyfx-fxmlloader (0.4.1 java)

Hope this helps
Bye ! 
JCLL

==============
require 'jrubyfx'

fxml_root File.dirname(__FILE__)

class Test < JRubyFX::Application

  def start(stage)
    with(stage, title: 'test_1') do
      fxml MyController
    end
    stage.show
  end
end

class MyController
  include JRubyFX::Controller
  fxml 'test_1.fxml'

  on :start do
    @label_1.text="started"
  end

  on :stop do
    @label_1.text="stopped"
  end

end

Test.launch
=============================
<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.control.Button?>
<?import javafx.scene.control.Label?>
<?import javafx.scene.control.Menu?>
<?import javafx.scene.control.MenuBar?>
<?import javafx.scene.control.MenuItem?>
<?import javafx.scene.control.SeparatorMenuItem?>
<?import javafx.scene.layout.AnchorPane?>
<?import javafx.scene.layout.VBox?>
<?import javafx.scene.text.Font?>

<VBox prefHeight="400.0" prefWidth="640.0" xmlns="http://javafx.com/javafx/8.0.65" xmlns:fx="http://javafx.com/fxml/1">
  <children>
    <MenuBar VBox.vgrow="NEVER">
      <menus>
        <Menu mnemonicParsing="false" text="File">
          <items>
            <MenuItem mnemonicParsing="false" text="New" />
            <MenuItem mnemonicParsing="false" text="Open…" />
            <Menu mnemonicParsing="false" text="Open Recent" />
            <SeparatorMenuItem mnemonicParsing="false" />
            <MenuItem mnemonicParsing="false" text="Close" />
            <MenuItem mnemonicParsing="false" text="Save" />
            <MenuItem mnemonicParsing="false" text="Save As…" />
            <MenuItem mnemonicParsing="false" text="Revert" />
            <SeparatorMenuItem mnemonicParsing="false" />
            <MenuItem mnemonicParsing="false" text="Preferences…" />
            <SeparatorMenuItem mnemonicParsing="false" />
            <MenuItem mnemonicParsing="false" text="Quit" />
          </items>
        </Menu>
        <Menu mnemonicParsing="false" text="Edit">
          <items>
            <MenuItem mnemonicParsing="false" text="Undo" />
            <MenuItem mnemonicParsing="false" text="Redo" />
            <SeparatorMenuItem mnemonicParsing="false" />
            <MenuItem mnemonicParsing="false" text="Cut" />
            <MenuItem mnemonicParsing="false" text="Copy" />
            <MenuItem mnemonicParsing="false" text="Paste" />
            <MenuItem mnemonicParsing="false" text="Delete" />
            <SeparatorMenuItem mnemonicParsing="false" />
            <MenuItem mnemonicParsing="false" text="Select All" />
            <MenuItem mnemonicParsing="false" text="Unselect All" />
          </items>
        </Menu>
        <Menu mnemonicParsing="false" text="Help">
          <items>
            <MenuItem mnemonicParsing="false" text="About MyHelloApp" />
          </items>
        </Menu>
      </menus>
    </MenuBar>
    <AnchorPane maxHeight="-1.0" maxWidth="-1.0" prefHeight="-1.0" prefWidth="-1.0" VBox.vgrow="ALWAYS">
      <children>
        <Label  fx:id="label_1" alignment="CENTER" layoutX="269.0" layoutY="24.0" style="&#10;" text="Control" textAlignment="CENTER" textFill="#9f9f9f" wrapText="true">
          <font>
            <Font size="18.0" />
          </font>
        </Label>
            <Button  onAction="#start" layoutX="78.0" layoutY="62.0" mnemonicParsing="false" text="start" AnchorPane.bottomAnchor="282.0" AnchorPane.leftAnchor="78.0" AnchorPane.rightAnchor="503.0" AnchorPane.topAnchor="62.0" />
            <Button  onAction="#stop" layoutX="152.0" layoutY="62.0" mnemonicParsing="false" text="Stop" />
      </children>
    </AnchorPane>
  </children>
</VBox>

**Comment by byteit101** [comment]
Please use the jrubyfx issue tracker.

https://github.com/jruby/jrubyfx/issues/111
